// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKGD5csfZoXnxTsgPEs0ztA3OIlgZBawc',
    appId: '1:1094098700649:web:ffb98045b4f0d7cd1995f8',
    messagingSenderId: '1094098700649',
    projectId: 'waste-management-80fa4',
    authDomain: 'waste-management-80fa4.firebaseapp.com',
    storageBucket: 'waste-management-80fa4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1u6LBD83yH_nRUSkM-lR1nrra7pQ3s1c',
    appId: '1:1094098700649:android:1eaeb0f33cc5c5181995f8',
    messagingSenderId: '1094098700649',
    projectId: 'waste-management-80fa4',
    storageBucket: 'waste-management-80fa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOqr5eWHvmK8WaS-yjdNaYdNJBcxY1j4k',
    appId: '1:1094098700649:ios:18efd179750c195a1995f8',
    messagingSenderId: '1094098700649',
    projectId: 'waste-management-80fa4',
    storageBucket: 'waste-management-80fa4.appspot.com',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOqr5eWHvmK8WaS-yjdNaYdNJBcxY1j4k',
    appId: '1:1094098700649:ios:18efd179750c195a1995f8',
    messagingSenderId: '1094098700649',
    projectId: 'waste-management-80fa4',
    storageBucket: 'waste-management-80fa4.appspot.com',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKGD5csfZoXnxTsgPEs0ztA3OIlgZBawc',
    appId: '1:1094098700649:web:9b74cf7db3feacd01995f8',
    messagingSenderId: '1094098700649',
    projectId: 'waste-management-80fa4',
    authDomain: 'waste-management-80fa4.firebaseapp.com',
    storageBucket: 'waste-management-80fa4.appspot.com',
  );
}
